Label discordant samples
Sage-Bionetworks/sageseqr pull request #135
Opened 2021-04-21 18:49 UTC by kelshmo

Fixes #130. Adds sample names to the output of `plot_sexcheck_pca()`.

2021-04-23 16:43 UTC, jgockley62 requested changes
There seems to be some. limitations on cohorts with large amounts of batches (point style variants) and for some reason different tissues (colors) are not displayed either.
![image](https://user-images.githubusercontent.com/7923935/115903379-5d837a00-a418-11eb-8715-e218f5fcef13.png)

2021-04-24 02:36 UTC, kelshmo commented
This PR adds labels to the `plot_sexcheck_pca` function, but I think you have `identify_outliers` plotted above. If yes, can you open an issue to track the issues with color and point types?

2021-04-26 18:32 UTC, jgockley62 commented
Looks alright! 
![image](https://user-images.githubusercontent.com/7923935/116133010-13520100-a683-11eb-84c0-ddff522bcd33.png)

2021-04-26 18:32 UTC, jgockley62 approved these changes

2021-04-30 22:02 UTC, merged