Biomart pull rec
Sage-Bionetworks/sageseqr pull request #169
Opened 2021-09-22 20:19 UTC by jgockley62

There's 3 ways to import a biomart file now.
  1) Pre-stored on Synapse
  2) Generate from biomart
  3) Build de novo from a GTF and FASTA file stored on synapse

-- Test GTF and FASTA:
      gtf <- synapser::synGet('syn20692159')
      genome <- synapser::synGet('syn20696945')

There's 2 types of biomart objects that the user can build:
  1) Consider only the exonic gene regions in the length and GC content 
  2) Consider only the entire transcript (exonic+Intronic) gene regions in the length and GC content

2021-10-15 22:26 UTC, kelshmo requested changes
For now, just looked through the files you have committed here. There are several files committed erroneously.  biomart_results.csv should not be in this repository. Same with the drake files and config.yml in the inst directory. Please remove the files and I will finish the review!

2021-10-15 22:26 UTC, kelshmo commented on initialize.R
> +Sys.setenv(R_CONFIG_ACTIVE = "ihab")
I think you added this script in error?

2021-10-15 22:26 UTC, kelshmo commented on inst/config.yml
> +default:
The config is not stored in the inst/ directory, it is stored at root.

2021-11-12 22:10 UTC, kelshmo commented on config.yml
> +    fataVersion: 1
Since we determined they are specific, I don't think they should be noted in this config as the files are private.

2021-11-12 22:13 UTC, kelshmo commented
@jgockley62  There are some additional comments to address. I also suggest writing a vignette called "Creating the gene annotations files" and describe some of these decision points. It would be helpful to note that the fasta output from alignment can be used as input here.

2021-11-16 20:28 UTC, jgockley62 commented on R/functions.R
> +#' Finds gene IDs in the filtered counts which were removed in cqn normalization
Yeah a decent redundancy just in case. Always the outside possibility that there's a custom GTF issue ie. Gene name not specified

2021-11-16 20:29 UTC, jgockley62 commented on R/functions.R
> +      rm(cl)
Proper stop, start, and removal helps prevent memory errors

2021-11-16 20:58 UTC, merged